# golangci-lint configuration

run:
  concurrency: 4
  timeout: 20s
  issues-exit-code: 2
  tests: false
  modules-download-mode: readonly
  go: "1.17"

output:
  formats:
    - format: github-actions

linters:
  disable:
    - tagliatelle
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style

  fast: true

issues:
  exclude-rules:
    - linters:
        - lll
      source: "BusinessCategory"
  fix: true
  new: true

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - "$gostd"
          - github.com/google
          - github.com/spf13
          - github.com/avocatl
          - golang.org/x/oauth2
          - github.com/VictorAvelar
      tests:
        files:
          - "$test"
        allow:
          - "github.com/stretchr/testify"
