package commands

// Available command arguments.
const (
	AmountCurrencyArg = "amount-currency"
	AmountValueArg    = "amount-value"
	BillingCountryArg = "billing-country"
	CancelableArg     = "cancelable"
	CurrencyArg       = "currency"
	CustomerIDArg     = "customer"
	DescriptionArg    = "description"
	EmbedArg          = "embed"
	EmailArg          = "email"
	FieldsArg         = "fields"
	FromArg           = "from"
	IDArg             = "id"
	IncludeArg        = "include"
	InvoiceArg        = "invoice"
	LimitArg          = "limit"
	LocaleArg         = "locale"
	MandateIDArg      = "mandate"
	MetadataArg       = "metadata"
	MethodArg         = "method"
	NameArg           = "name"
	PaymentArg        = "payment"
	PermissionArg     = "permission"
	ReferenceArg      = "reference"
	RedirectURLArg    = "redirect-to"
	RPMToCountryArg   = "restrict-payment-to-country"
	ResourceArg       = "resource"
	SequenceTypeArg   = "sequence-type"
	WalletsArg        = "wallets"
	WebhookURLArg     = "webhook-url"
	YearArg           = "year"
)
